"""Behavior CI evidence emission for external robotics rollout engines."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from cybernetics.behavior_ci.artifacts import validate_bundle, write_bundle
from cybernetics.behavior_ci.schemas import (
    BehaviorCiResult,
    Check,
    CheckResult,
    EvalSpec,
    Event,
    HonestyProvenance,
    TrialObservation,
    TrialResult,
)
from cybernetics.behavior_ci.simulators.base import ReplayResult, looks_like_mp4

from .runtime_contracts import EpisodeManifest, RoboticsJobSpec


class RoboticsEvidenceError(RuntimeError):
    """A robotics run cannot produce an honest, valid evidence bundle."""


def write_robotics_behavior_bundle(
    job: RoboticsJobSpec,
    episodes: Sequence[EpisodeManifest],
    bundle_dir: str | Path,
    *,
    replay_videos: Mapping[str, bytes | str | Path] | None = None,
    artifact_url: str = "",
    allow_fixture_replay: bool = False,
) -> BehaviorCiResult:
    """Write a validated Behavior CI bundle from normalized episode manifests.

    The rollout engine owns simulation and recording. This function owns only
    evaluation checks, report rendering, and the stable evidence layout.
    """

    if not episodes:
        raise RoboticsEvidenceError("at least one episode manifest is required")
    if len(episodes) != job.rollout.episodes:
        raise RoboticsEvidenceError(
            f"expected {job.rollout.episodes} episode manifests, received {len(episodes)}"
        )

    eval_spec = _behavior_eval_spec(job)
    trials = [_trial(index, episode, eval_spec) for index, episode in enumerate(episodes)]
    status = "passed" if trials and all(trial.passed for trial in trials) else "failed"
    checks = {
        name: bool(trials) and all(trial.checks[name].passed for trial in trials)
        for name in eval_spec.checks
    }
    failures = [
        {"run": event.run, "code": event.code, "message": event.message}
        for trial in trials
        for event in trial.events
    ]
    aggregate = _aggregate_metrics(episodes)
    passed = sum(1 for trial in trials if trial.passed)
    result = BehaviorCiResult(
        status=status,
        behavior=job.evaluation.behavior,
        robot=str(job.metadata.get("robot_id", "unspecified")),
        world=job.simulator.package_id,
        scene_env=str(job.metadata.get("scene_env", job.task.package_id)),
        camera=job.recording.cameras[0] if job.recording.cameras else "runtime-default",
        policy=job.policy.deployment_id,
        policy_id=job.policy.deployment_id,
        policy_backend=job.policy.runtime_family,
        commit=job.task.source_ref,
        summary={
            "passed_runs": passed,
            "total_runs": len(trials),
            "failed_runs": len(trials) - passed,
            "world": job.simulator.package_id,
            "behavior": job.evaluation.behavior,
        },
        checks=checks,
        metrics=aggregate,
        failures=failures,
        trials=trials,
        honesty=HonestyProvenance(
            simulator_adapter="robotics-runtime",
            replay_source="robotics-runtime-video",
            policy_backend=job.policy.runtime_family,
            policy_backend_real_vla=job.policy.source == "worldlines",
            production_eval_path_used=True,
            scene_env=str(job.metadata.get("scene_env", job.task.package_id)),
            camera=job.recording.cameras[0] if job.recording.cameras else "runtime-default",
            notes=(
                "Generated by the provider-neutral Cybernetic Robotics Runtime from "
                "pinned job and episode manifests."
            ),
            task_id=job.task.task_id,
            task_version=job.job_hash(),
            eval_sha256=job.job_hash(),
            pins_verified=True,
        ),
    )

    replays, replay_source = _select_replays(
        trials,
        episodes,
        replay_videos or {},
        camera=result.camera,
        allow_fixture_replay=allow_fixture_replay,
    )
    result.honesty.replay_source = replay_source

    output = Path(bundle_dir)
    output.mkdir(parents=True, exist_ok=True)
    normalized = {
        "schema_version": "robotics-behavior-ci-normalized/v1",
        "job_hash": job.job_hash(),
        "job": job.to_dict(),
        "episodes": [episode.to_dict() for episode in episodes],
    }
    write_bundle(result, replays, eval_spec, normalized, output, artifact_url=artifact_url)
    _write_json(output / "robotics-job.json", job.to_dict())
    episodes_dir = output / "episodes"
    episodes_dir.mkdir(exist_ok=True)
    for episode in episodes:
        _write_json(episodes_dir / f"{episode.episode_id}.json", episode.to_dict())

    problems = validate_bundle(output, result)
    if problems:
        raise RoboticsEvidenceError("invalid Behavior CI bundle: " + "; ".join(problems))
    return result


def _behavior_eval_spec(job: RoboticsJobSpec) -> EvalSpec:
    return EvalSpec(
        schema_version="behavior-ci-eval/v1",
        world=job.simulator.package_id,
        behavior=job.evaluation.behavior,
        runs=job.rollout.episodes,
        checks={
            name: Check(
                name=name,
                metric=check.metric,
                operator=check.operator,
                value=check.value,
                required=check.required,
            )
            for name, check in job.evaluation.checks.items()
        },
    )


def _trial(index: int, episode: EpisodeManifest, spec: EvalSpec) -> TrialResult:
    numeric_metrics = {
        key: float(value)
        for key, value in episode.metrics.items()
        if isinstance(value, (int, float, bool))
    }
    missing = [
        check.metric for check in spec.checks.values() if check.metric not in numeric_metrics
    ]
    if episode.status in {"crashed", "cancelled", "failed"} or missing:
        message = episode.error_message or (
            f"episode status is {episode.status}"
            if not missing
            else f"episode did not emit required metrics: {sorted(set(missing))}"
        )
        return TrialResult(
            run=index,
            passed=False,
            checks={
                name: CheckResult(
                    passed=False,
                    metric=check.metric,
                    actual=numeric_metrics.get(check.metric),
                    operator=check.operator,
                    expected=check.value,
                    required=check.required,
                )
                for name, check in spec.checks.items()
            },
            metrics=numeric_metrics,
            events=[
                Event(
                    run=index,
                    time_seconds=0.0,
                    code=episode.error_code or "EPISODE_FAILED",
                    message=message,
                )
            ],
            trajectory_id=episode.episode_id,
        )

    from cybernetics.behavior_ci.evaluator import evaluate_trial

    return evaluate_trial(
        TrialObservation(
            run=index,
            metrics=numeric_metrics,
            trajectory_id=episode.episode_id,
        ),
        spec,
    )


def _aggregate_metrics(episodes: Sequence[EpisodeManifest]) -> dict[str, Any]:
    keys = sorted(
        {
            key
            for episode in episodes
            for key, value in episode.metrics.items()
            if isinstance(value, (int, float, bool))
        }
    )
    result: dict[str, Any] = {}
    for key in keys:
        values = [
            float(episode.metrics[key])
            for episode in episodes
            if isinstance(episode.metrics.get(key), (int, float, bool))
        ]
        if values:
            result[key] = sum(values) / len(values)
    result["episodes"] = len(episodes)
    return result


def _select_replays(
    trials: Sequence[TrialResult],
    episodes: Sequence[EpisodeManifest],
    replay_videos: Mapping[str, bytes | str | Path],
    *,
    camera: str,
    allow_fixture_replay: bool,
) -> tuple[list[ReplayResult], str]:
    selected: list[tuple[str, EpisodeManifest]] = []
    failed_index = next((index for index, trial in enumerate(trials) if not trial.passed), None)
    passed_index = next((index for index, trial in enumerate(trials) if trial.passed), None)
    if failed_index is not None:
        selected.append(("replay-failed", episodes[failed_index]))
    if passed_index is not None:
        selected.append(("replay-passed", episodes[passed_index]))
    if not selected:
        selected.append(("replay-failed", episodes[0]))

    replays: list[ReplayResult] = []
    fixture_used = False
    for name, episode in selected:
        data = _read_replay(replay_videos.get(episode.episode_id))
        is_fixture = False
        if data is None or not looks_like_mp4(data):
            if not allow_fixture_replay:
                raise RoboticsEvidenceError(
                    f"episode {episode.episode_id!r} is missing a valid MP4 replay"
                )
            data = _fixture_mp4(episode.episode_id)
            fixture_used = True
            is_fixture = True
        replays.append(
            ReplayResult(
                name=name,
                data=data,
                source="fixture-generated" if is_fixture else "robotics-runtime-video",
                camera=camera,
            )
        )
    return replays, "fixture-generated" if fixture_used else "robotics-runtime-video"


def _read_replay(source: bytes | str | Path | None) -> bytes | None:
    if isinstance(source, bytes):
        return source
    if isinstance(source, (str, Path)):
        path = Path(source)
        if path.is_file():
            return path.read_bytes()
    return None


def _fixture_mp4(label: str) -> bytes:
    ftyp = b"\x00\x00\x00\x18ftypisom\x00\x00\x02\x00isomiso2"
    return ftyp + b"\n[fixture-generated robotics replay: " + label.encode() + b"]\n"


def _write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")
